package com.kclm.owep.mapper;

import com.kclm.owep.entity.Advice;
import com.kclm.owep.entity.AdviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    long countByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int deleteByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int insert(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int insertSelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    List<Advice> selectByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    Advice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Advice record, @Param("example") AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Advice record, @Param("example") AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Advice record);
}