package com.kclm.owep.mapper;

import com.kclm.owep.entity.ChannelType;
import com.kclm.owep.entity.ChannelTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    long countByExample(ChannelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int deleteByExample(ChannelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int insert(ChannelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int insertSelective(ChannelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    List<ChannelType> selectByExample(ChannelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    ChannelType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChannelType record, @Param("example") ChannelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChannelType record, @Param("example") ChannelTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChannelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChannelType record);
}