package com.kclm.owep.mapper;

import com.kclm.owep.entity.ClassQuestion;
import com.kclm.owep.entity.ClassQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    long countByExample(ClassQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int deleteByExample(ClassQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int insert(ClassQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int insertSelective(ClassQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    List<ClassQuestion> selectByExample(ClassQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    ClassQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ClassQuestion record, @Param("example") ClassQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ClassQuestion record, @Param("example") ClassQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClassQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassQuestion record);
}