package com.kclm.owep.mapper;

import java.util.List;

import com.kclm.owep.entity.Clazz;
import org.apache.ibatis.annotations.Param;
/*********************
 * @Author: tanj
 * @Version : v1.0
 * @Create: 2020年7月06日 下午16:10:40
 * @Description 班级
 */
public interface ClazzMapper {

    /***
     * 增加一条记录
     * @param clazz
     * @return
     */
    int save(Clazz clazz);

    /***
     * 根据id删除一条记录
     * @param id
     * @return
     */
    int deleteByPrimaryKey(Integer id);

    /***
     *
     * @param record
     * @return
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int insertSelective(Clazz record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    Clazz selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Clazz record);
}