package com.kclm.owep.mapper;

import com.kclm.owep.entity.CourseReport;
import com.kclm.owep.entity.CourseReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    long countByExample(CourseReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int deleteByExample(CourseReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int insert(CourseReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int insertSelective(CourseReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    List<CourseReport> selectByExample(CourseReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    CourseReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CourseReport record, @Param("example") CourseReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CourseReport record, @Param("example") CourseReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CourseReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CourseReport record);
}