package com.kclm.owep.mapper;

import com.kclm.owep.entity.DbCopy;
import com.kclm.owep.entity.DbCopyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    long countByExample(DbCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int deleteByExample(DbCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int insert(DbCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int insertSelective(DbCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    List<DbCopy> selectByExample(DbCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    DbCopy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbCopy record, @Param("example") DbCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbCopy record, @Param("example") DbCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_db_copy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbCopy record);
}