package com.kclm.owep.mapper;

import com.kclm.owep.entity.Evaluate;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvaluateMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int insert(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int insertSelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    Evaluate selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Evaluate record);
}