package com.kclm.owep.mapper;

import com.kclm.owep.entity.HomeworkAnswer;
import com.kclm.owep.entity.HomeworkAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    long countByExample(HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int deleteByExample(HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int insert(HomeworkAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int insertSelective(HomeworkAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    List<HomeworkAnswer> selectByExample(HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    HomeworkAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HomeworkAnswer record, @Param("example") HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HomeworkAnswer record, @Param("example") HomeworkAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HomeworkAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HomeworkAnswer record);
}