package com.kclm.owep.mapper;

import com.kclm.owep.entity.Illegal;
import com.kclm.owep.entity.IllegalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IllegalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    long countByExample(IllegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int deleteByExample(IllegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int insert(Illegal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int insertSelective(Illegal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    List<Illegal> selectByExample(IllegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    Illegal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Illegal record, @Param("example") IllegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Illegal record, @Param("example") IllegalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Illegal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_illegal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Illegal record);
}