package com.kclm.owep.mapper;

import com.kclm.owep.entity.PlanManager;
import com.kclm.owep.entity.PlanManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlanManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    long countByExample(PlanManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int deleteByExample(PlanManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int insert(PlanManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int insertSelective(PlanManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    List<PlanManager> selectByExample(PlanManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    PlanManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlanManager record, @Param("example") PlanManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlanManager record, @Param("example") PlanManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlanManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlanManager record);
}