package com.kclm.owep.mapper;

import com.kclm.owep.entity.PlanManagerCourse;
import com.kclm.owep.entity.PlanManagerCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlanManagerCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    long countByExample(PlanManagerCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int deleteByExample(PlanManagerCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int insert(PlanManagerCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int insertSelective(PlanManagerCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    List<PlanManagerCourse> selectByExample(PlanManagerCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    PlanManagerCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlanManagerCourse record, @Param("example") PlanManagerCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlanManagerCourse record, @Param("example") PlanManagerCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlanManagerCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_planmanager_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlanManagerCourse record);
}