package com.kclm.owep.mapper;

import com.kclm.owep.entity.PollRecord;
import com.kclm.owep.entity.PollRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    long countByExample(PollRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int deleteByExample(PollRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int insert(PollRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int insertSelective(PollRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    List<PollRecord> selectByExample(PollRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    PollRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PollRecord record, @Param("example") PollRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PollRecord record, @Param("example") PollRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PollRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_poll_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PollRecord record);
}