/********************************
 *版权所有 CopyRight(c) 快程乐码信息有限公司所有，未经授权，不得复制、转发
 */
package com.kclm.owep.mapper;

import com.kclm.owep.entity.Profession;
import java.util.List;
import org.apache.ibatis.annotations.Param;
/*********************
 * @Author: tanj
 * @Version : v1.0
 * @Create: 2020年7月06日 上午17:30:40
 * @Description 专业方向
 */
public interface ProfessionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated
     */
    Profession selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Profession record);
}