package com.kclm.owep.mapper;

import com.kclm.owep.entity.QuestionReply;
import com.kclm.owep.entity.QuestionReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    long countByExample(QuestionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int deleteByExample(QuestionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int insert(QuestionReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int insertSelective(QuestionReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    List<QuestionReply> selectByExample(QuestionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    QuestionReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestionReply record, @Param("example") QuestionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestionReply record, @Param("example") QuestionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestionReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionReply record);
}