package com.kclm.owep.mapper;

import com.kclm.owep.entity.ResourceType;
import com.kclm.owep.entity.ResourceTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    long countByExample(ResourceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int deleteByExample(ResourceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int insert(ResourceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int insertSelective(ResourceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    List<ResourceType> selectByExample(ResourceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    ResourceType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResourceType record, @Param("example") ResourceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResourceType record, @Param("example") ResourceTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceType record);
}