package com.kclm.owep.mapper;

import com.kclm.owep.entity.StudyRecord;
import com.kclm.owep.entity.StudyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    long countByExample(StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int deleteByExample(StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int insert(StudyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int insertSelective(StudyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    List<StudyRecord> selectByExample(StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    StudyRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StudyRecord record, @Param("example") StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StudyRecord record, @Param("example") StudyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_studyrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudyRecord record);
}