package com.kclm.owep.mapper;

import com.kclm.owep.entity.TeacherPoll;
import com.kclm.owep.entity.TeacherPollExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherPollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    long countByExample(TeacherPollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int deleteByExample(TeacherPollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int insert(TeacherPoll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int insertSelective(TeacherPoll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    List<TeacherPoll> selectByExample(TeacherPollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    TeacherPoll selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TeacherPoll record, @Param("example") TeacherPollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TeacherPoll record, @Param("example") TeacherPollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherPoll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_poll
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherPoll record);
}