package com.kclm.owep.mapper;

import com.kclm.owep.entity.VideoQuestion;
import com.kclm.owep.entity.VideoQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    long countByExample(VideoQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int deleteByExample(VideoQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int insert(VideoQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int insertSelective(VideoQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    List<VideoQuestion> selectByExample(VideoQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    VideoQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VideoQuestion record, @Param("example") VideoQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VideoQuestion record, @Param("example") VideoQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VideoQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoQuestion record);
}