package com.kclm.owep.mapper;

import com.kclm.owep.entity.VideoCollect;
import com.kclm.owep.entity.VideoCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    long countByExample(VideoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int deleteByExample(VideoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int insert(VideoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int insertSelective(VideoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    List<VideoCollect> selectByExample(VideoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    VideoCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VideoCollect record, @Param("example") VideoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VideoCollect record, @Param("example") VideoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VideoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoCollect record);
}