package com.kclm.owep.entity;

import java.util.Date;

public class Advice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.advice_content
     *
     * @mbg.generated
     */
    private String adviceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.suggest_name
     *
     * @mbg.generated
     */
    private Integer suggestName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.id
     *
     * @return the value of t_advice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.id
     *
     * @param id the value for t_advice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.email
     *
     * @return the value of t_advice.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.email
     *
     * @param email the value for t_advice.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.advice_content
     *
     * @return the value of t_advice.advice_content
     *
     * @mbg.generated
     */
    public String getAdviceContent() {
        return adviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.advice_content
     *
     * @param adviceContent the value for t_advice.advice_content
     *
     * @mbg.generated
     */
    public void setAdviceContent(String adviceContent) {
        this.adviceContent = adviceContent == null ? null : adviceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.suggest_name
     *
     * @return the value of t_advice.suggest_name
     *
     * @mbg.generated
     */
    public Integer getSuggestName() {
        return suggestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.suggest_name
     *
     * @param suggestName the value for t_advice.suggest_name
     *
     * @mbg.generated
     */
    public void setSuggestName(Integer suggestName) {
        this.suggestName = suggestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.create_time
     *
     * @return the value of t_advice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.create_time
     *
     * @param createTime the value for t_advice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.last_access_time
     *
     * @return the value of t_advice.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.last_access_time
     *
     * @param lastAccessTime the value for t_advice.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.version
     *
     * @return the value of t_advice.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.version
     *
     * @param version the value for t_advice.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}