package com.kclm.owep.entity;

import java.util.Date;

public class ChannelType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_type.channel_type_name
     *
     * @mbg.generated
     */
    private String channelTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_type.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_type.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_type.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_type.id
     *
     * @return the value of t_channel_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_type.id
     *
     * @param id the value for t_channel_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_type.channel_type_name
     *
     * @return the value of t_channel_type.channel_type_name
     *
     * @mbg.generated
     */
    public String getChannelTypeName() {
        return channelTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_type.channel_type_name
     *
     * @param channelTypeName the value for t_channel_type.channel_type_name
     *
     * @mbg.generated
     */
    public void setChannelTypeName(String channelTypeName) {
        this.channelTypeName = channelTypeName == null ? null : channelTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_type.create_time
     *
     * @return the value of t_channel_type.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_type.create_time
     *
     * @param createTime the value for t_channel_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_type.version
     *
     * @return the value of t_channel_type.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_type.version
     *
     * @param version the value for t_channel_type.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_type.last_access_time
     *
     * @return the value of t_channel_type.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_type.last_access_time
     *
     * @param lastAccessTime the value for t_channel_type.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}