package com.kclm.owep.entity;

import java.util.Date;

public class Chapter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.chapter_number
     *
     * @mbg.generated
     */
    private String chapterNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.chapter_name
     *
     * @mbg.generated
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.
chapter_image_url
     *
     * @mbg.generated
     */
    private String 
chapterImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.chapter_status
     *
     * @mbg.generated
     */
    private Integer chapterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.chapter_desc
     *
     * @mbg.generated
     */
    private String chapterDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.
create_time
     *
     * @mbg.generated
     */
    private Date 
createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.video_status
     *
     * @mbg.generated
     */
    private Integer videoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.fk_course_id
     *
     * @mbg.generated
     */
    private Integer fkCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.id
     *
     * @return the value of t_chapter.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.id
     *
     * @param id the value for t_chapter.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.chapter_number
     *
     * @return the value of t_chapter.chapter_number
     *
     * @mbg.generated
     */
    public String getChapterNumber() {
        return chapterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.chapter_number
     *
     * @param chapterNumber the value for t_chapter.chapter_number
     *
     * @mbg.generated
     */
    public void setChapterNumber(String chapterNumber) {
        this.chapterNumber = chapterNumber == null ? null : chapterNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.chapter_name
     *
     * @return the value of t_chapter.chapter_name
     *
     * @mbg.generated
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.chapter_name
     *
     * @param chapterName the value for t_chapter.chapter_name
     *
     * @mbg.generated
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.
chapter_image_url
     *
     * @return the value of t_chapter.
chapter_image_url
     *
     * @mbg.generated
     */
    public String get
chapterImageUrl() {
        return 
chapterImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.
chapter_image_url
     *
     * @param 
chapterImageUrl the value for t_chapter.
chapter_image_url
     *
     * @mbg.generated
     */
    public void set
chapterImageUrl(String 
chapterImageUrl) {
        this.
chapterImageUrl = 
chapterImageUrl == null ? null : 
chapterImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.chapter_status
     *
     * @return the value of t_chapter.chapter_status
     *
     * @mbg.generated
     */
    public Integer getChapterStatus() {
        return chapterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.chapter_status
     *
     * @param chapterStatus the value for t_chapter.chapter_status
     *
     * @mbg.generated
     */
    public void setChapterStatus(Integer chapterStatus) {
        this.chapterStatus = chapterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.chapter_desc
     *
     * @return the value of t_chapter.chapter_desc
     *
     * @mbg.generated
     */
    public String getChapterDesc() {
        return chapterDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.chapter_desc
     *
     * @param chapterDesc the value for t_chapter.chapter_desc
     *
     * @mbg.generated
     */
    public void setChapterDesc(String chapterDesc) {
        this.chapterDesc = chapterDesc == null ? null : chapterDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.
create_time
     *
     * @return the value of t_chapter.
create_time
     *
     * @mbg.generated
     */
    public Date get
createTime() {
        return 
createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.
create_time
     *
     * @param 
createTime the value for t_chapter.
create_time
     *
     * @mbg.generated
     */
    public void set
createTime(Date 
createTime) {
        this.
createTime = 
createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.video_status
     *
     * @return the value of t_chapter.video_status
     *
     * @mbg.generated
     */
    public Integer getVideoStatus() {
        return videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.video_status
     *
     * @param videoStatus the value for t_chapter.video_status
     *
     * @mbg.generated
     */
    public void setVideoStatus(Integer videoStatus) {
        this.videoStatus = videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.fk_course_id
     *
     * @return the value of t_chapter.fk_course_id
     *
     * @mbg.generated
     */
    public Integer getFkCourseId() {
        return fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.fk_course_id
     *
     * @param fkCourseId the value for t_chapter.fk_course_id
     *
     * @mbg.generated
     */
    public void setFkCourseId(Integer fkCourseId) {
        this.fkCourseId = fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.delete
     *
     * @return the value of t_chapter.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.delete
     *
     * @param delete the value for t_chapter.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.version
     *
     * @return the value of t_chapter.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.version
     *
     * @param version the value for t_chapter.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.last_access_time
     *
     * @return the value of t_chapter.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.last_access_time
     *
     * @param lastAccessTime the value for t_chapter.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}