package com.kclm.owep.entity;

import java.util.Date;

public class ClassQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.question_title
     *
     * @mbg.generated
     */
    private String questionTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.question_desc
     *
     * @mbg.generated
     */
    private String questionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.question_status
     *
     * @mbg.generated
     */
    private Integer questionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.correlated_course
     *
     * @mbg.generated
     */
    private String correlatedCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.fk_video_id
     *
     * @mbg.generated
     */
    private Integer fkVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.fk_course_id
     *
     * @mbg.generated
     */
    private Integer fkCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.course_number
     *
     * @mbg.generated
     */
    private Integer courseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_question.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.id
     *
     * @return the value of t_class_question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.id
     *
     * @param id the value for t_class_question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.question_title
     *
     * @return the value of t_class_question.question_title
     *
     * @mbg.generated
     */
    public String getQuestionTitle() {
        return questionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.question_title
     *
     * @param questionTitle the value for t_class_question.question_title
     *
     * @mbg.generated
     */
    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle == null ? null : questionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.question_desc
     *
     * @return the value of t_class_question.question_desc
     *
     * @mbg.generated
     */
    public String getQuestionDesc() {
        return questionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.question_desc
     *
     * @param questionDesc the value for t_class_question.question_desc
     *
     * @mbg.generated
     */
    public void setQuestionDesc(String questionDesc) {
        this.questionDesc = questionDesc == null ? null : questionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.question_status
     *
     * @return the value of t_class_question.question_status
     *
     * @mbg.generated
     */
    public Integer getQuestionStatus() {
        return questionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.question_status
     *
     * @param questionStatus the value for t_class_question.question_status
     *
     * @mbg.generated
     */
    public void setQuestionStatus(Integer questionStatus) {
        this.questionStatus = questionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.correlated_course
     *
     * @return the value of t_class_question.correlated_course
     *
     * @mbg.generated
     */
    public String getCorrelatedCourse() {
        return correlatedCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.correlated_course
     *
     * @param correlatedCourse the value for t_class_question.correlated_course
     *
     * @mbg.generated
     */
    public void setCorrelatedCourse(String correlatedCourse) {
        this.correlatedCourse = correlatedCourse == null ? null : correlatedCourse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.fk_student_id
     *
     * @return the value of t_class_question.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.fk_student_id
     *
     * @param fkStudentId the value for t_class_question.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.fk_video_id
     *
     * @return the value of t_class_question.fk_video_id
     *
     * @mbg.generated
     */
    public Integer getFkVideoId() {
        return fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.fk_video_id
     *
     * @param fkVideoId the value for t_class_question.fk_video_id
     *
     * @mbg.generated
     */
    public void setFkVideoId(Integer fkVideoId) {
        this.fkVideoId = fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.fk_course_id
     *
     * @return the value of t_class_question.fk_course_id
     *
     * @mbg.generated
     */
    public Integer getFkCourseId() {
        return fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.fk_course_id
     *
     * @param fkCourseId the value for t_class_question.fk_course_id
     *
     * @mbg.generated
     */
    public void setFkCourseId(Integer fkCourseId) {
        this.fkCourseId = fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.course_number
     *
     * @return the value of t_class_question.course_number
     *
     * @mbg.generated
     */
    public Integer getCourseNumber() {
        return courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.course_number
     *
     * @param courseNumber the value for t_class_question.course_number
     *
     * @mbg.generated
     */
    public void setCourseNumber(Integer courseNumber) {
        this.courseNumber = courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.create_time
     *
     * @return the value of t_class_question.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.create_time
     *
     * @param createTime the value for t_class_question.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.version
     *
     * @return the value of t_class_question.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.version
     *
     * @param version the value for t_class_question.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_question.last_access_time
     *
     * @return the value of t_class_question.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_question.last_access_time
     *
     * @param lastAccessTime the value for t_class_question.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}