package com.kclm.owep.entity;


import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import java.util.Date;

public class Clazz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.calss_number
     *
     * @mbg.generated
     */
    private String calssNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_status
     *
     * @mbg.generated
     */
    private Integer classStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.institute_name
     *
     * @mbg.generated
     */
    private String instituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.branch_name
     *
     * @mbg.generated
     */
    private String branchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_desc
     *
     * @mbg.generated
     */
    private String classDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.teacher_name
     *
     * @mbg.generated
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.fk_ profession_id
     *
     * @mbg.generated
     */
    private Integer fkProfessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.old_class_name
     *
     * @mbg.generated
     */
    private String oldClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.old_class_num
     *
     * @mbg.generated
     */
    private String oldClassNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.id
     *
     * @return the value of t_class.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.id
     *
     * @param id the value for t_class.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.calss_number
     *
     * @return the value of t_class.calss_number
     *
     * @mbg.generated
     */
    public String getCalssNumber() {
        return calssNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.calss_number
     *
     * @param calssNumber the value for t_class.calss_number
     *
     * @mbg.generated
     */
    public void setCalssNumber(String calssNumber) {
        this.calssNumber = calssNumber == null ? null : calssNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_name
     *
     * @return the value of t_class.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_name
     *
     * @param className the value for t_class.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.start_time
     *
     * @return the value of t_class.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.start_time
     *
     * @param startTime the value for t_class.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.end_time
     *
     * @return the value of t_class.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.end_time
     *
     * @param endTime the value for t_class.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_status
     *
     * @return the value of t_class.class_status
     *
     * @mbg.generated
     */
    public Integer getClassStatus() {
        return classStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_status
     *
     * @param classStatus the value for t_class.class_status
     *
     * @mbg.generated
     */
    public void setClassStatus(Integer classStatus) {
        this.classStatus = classStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.institute_name
     *
     * @return the value of t_class.institute_name
     *
     * @mbg.generated
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.institute_name
     *
     * @param instituteName the value for t_class.institute_name
     *
     * @mbg.generated
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName == null ? null : instituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.branch_name
     *
     * @return the value of t_class.branch_name
     *
     * @mbg.generated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.branch_name
     *
     * @param branchName the value for t_class.branch_name
     *
     * @mbg.generated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_desc
     *
     * @return the value of t_class.class_desc
     *
     * @mbg.generated
     */
    public String getClassDesc() {
        return classDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_desc
     *
     * @param classDesc the value for t_class.class_desc
     *
     * @mbg.generated
     */
    public void setClassDesc(String classDesc) {
        this.classDesc = classDesc == null ? null : classDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.teacher_name
     *
     * @return the value of t_class.teacher_name
     *
     * @mbg.generated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.teacher_name
     *
     * @param teacherName the value for t_class.teacher_name
     *
     * @mbg.generated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.fk_ profession_id
     *
     * @return the value of t_class.fk_ profession_id
     *
     * @mbg.generated
     */
    public Integer getFkProfessionId() {
        return fkProfessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.fk_ profession_id
     *
     * @param fkProfessionId the value for t_class.fk_ profession_id
     *
     * @mbg.generated
     */
    public void setFkProfessionId(Integer fkProfessionId) {
        this.fkProfessionId = fkProfessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.delete
     *
     * @return the value of t_class.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.delete
     *
     * @param delete the value for t_class.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.version
     *
     * @return the value of t_class.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.version
     *
     * @param version the value for t_class.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.create_time
     *
     * @return the value of t_class.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.create_time
     *
     * @param createTime the value for t_class.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.last_access_time
     *
     * @return the value of t_class.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.last_access_time
     *
     * @param lastAccessTime the value for t_class.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.old_class_name
     *
     * @return the value of t_class.old_class_name
     *
     * @mbg.generated
     */
    public String getOldClassName() {
        return oldClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.old_class_name
     *
     * @param oldClassName the value for t_class.old_class_name
     *
     * @mbg.generated
     */
    public void setOldClassName(String oldClassName) {
        this.oldClassName = oldClassName == null ? null : oldClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.old_class_num
     *
     * @return the value of t_class.old_class_num
     *
     * @mbg.generated
     */
    public String getOldClassNum() {
        return oldClassNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.old_class_num
     *
     * @param oldClassNum the value for t_class.old_class_num
     *
     * @mbg.generated
     */
    public void setOldClassNum(String oldClassNum) {
        this.oldClassNum = oldClassNum == null ? null : oldClassNum.trim();
    }
}

