package com.kclm.owep.entity;

import java.time.LocalDateTime;

/*********************
 * @Author: tanj
 * @Version : v1.0
 * @Create: 2020年6月29日 上午10:10:40
 * @Description ClassReport generated by hbm2java
 */
public class ClazzReport implements java.io.Serializable {

	private Integer reportId;
	private String classProg;
	private int classId;
	private int version = 1;  //版本号
	private LocalDateTime createTime = LocalDateTime.now();  //创建时间
	private LocalDateTime lastAccessTime; //最后一次访问时间

}
