package com.kclm.owep.entity;

import java.util.Date;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_phone
     *
     * @mbg.generated
     */
    private String clientPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_experience
     *
     * @mbg.generated
     */
    private String clientExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.salseman_describe
     *
     * @mbg.generated
     */
    private String salsemanDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.advance_pay
     *
     * @mbg.generated
     */
    private Double advancePay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.total_pay
     *
     * @mbg.generated
     */
    private Double totalPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.month_pay
     *
     * @mbg.generated
     */
    private Double monthPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.pay_ment
     *
     * @mbg.generated
     */
    private Integer payMent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.is_assign_class
     *
     * @mbg.generated
     */
    private Integer isAssignClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_email
     *
     * @mbg.generated
     */
    private String clientEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.loan_status
     *
     * @mbg.generated
     */
    private Integer loanStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.loan
     *
     * @mbg.generated
     */
    private Double loan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.interview_time
     *
     * @mbg.generated
     */
    private Date interviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_state
     *
     * @mbg.generated
     */
    private Integer clientState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.fk_profession_id
     *
     * @mbg.generated
     */
    private Integer fkProfessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.sign_time
     *
     * @mbg.generated
     */
    private String signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.fk_channel_id
     *
     * @mbg.generated
     */
    private Integer fkChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.fk_user_id
     *
     * @mbg.generated
     */
    private Integer fkUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.id
     *
     * @return the value of t_client.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.id
     *
     * @param id the value for t_client.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_name
     *
     * @return the value of t_client.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_name
     *
     * @param clientName the value for t_client.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_phone
     *
     * @return the value of t_client.client_phone
     *
     * @mbg.generated
     */
    public String getClientPhone() {
        return clientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_phone
     *
     * @param clientPhone the value for t_client.client_phone
     *
     * @mbg.generated
     */
    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone == null ? null : clientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.gender
     *
     * @return the value of t_client.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.gender
     *
     * @param gender the value for t_client.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_experience
     *
     * @return the value of t_client.client_experience
     *
     * @mbg.generated
     */
    public String getClientExperience() {
        return clientExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_experience
     *
     * @param clientExperience the value for t_client.client_experience
     *
     * @mbg.generated
     */
    public void setClientExperience(String clientExperience) {
        this.clientExperience = clientExperience == null ? null : clientExperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.salseman_describe
     *
     * @return the value of t_client.salseman_describe
     *
     * @mbg.generated
     */
    public String getSalsemanDescribe() {
        return salsemanDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.salseman_describe
     *
     * @param salsemanDescribe the value for t_client.salseman_describe
     *
     * @mbg.generated
     */
    public void setSalsemanDescribe(String salsemanDescribe) {
        this.salsemanDescribe = salsemanDescribe == null ? null : salsemanDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.advance_pay
     *
     * @return the value of t_client.advance_pay
     *
     * @mbg.generated
     */
    public Double getAdvancePay() {
        return advancePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.advance_pay
     *
     * @param advancePay the value for t_client.advance_pay
     *
     * @mbg.generated
     */
    public void setAdvancePay(Double advancePay) {
        this.advancePay = advancePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.create_time
     *
     * @return the value of t_client.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.create_time
     *
     * @param createTime the value for t_client.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.total_pay
     *
     * @return the value of t_client.total_pay
     *
     * @mbg.generated
     */
    public Double getTotalPay() {
        return totalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.total_pay
     *
     * @param totalPay the value for t_client.total_pay
     *
     * @mbg.generated
     */
    public void setTotalPay(Double totalPay) {
        this.totalPay = totalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.month_pay
     *
     * @return the value of t_client.month_pay
     *
     * @mbg.generated
     */
    public Double getMonthPay() {
        return monthPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.month_pay
     *
     * @param monthPay the value for t_client.month_pay
     *
     * @mbg.generated
     */
    public void setMonthPay(Double monthPay) {
        this.monthPay = monthPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.pay_ment
     *
     * @return the value of t_client.pay_ment
     *
     * @mbg.generated
     */
    public Integer getPayMent() {
        return payMent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.pay_ment
     *
     * @param payMent the value for t_client.pay_ment
     *
     * @mbg.generated
     */
    public void setPayMent(Integer payMent) {
        this.payMent = payMent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.is_assign_class
     *
     * @return the value of t_client.is_assign_class
     *
     * @mbg.generated
     */
    public Integer getIsAssignClass() {
        return isAssignClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.is_assign_class
     *
     * @param isAssignClass the value for t_client.is_assign_class
     *
     * @mbg.generated
     */
    public void setIsAssignClass(Integer isAssignClass) {
        this.isAssignClass = isAssignClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_email
     *
     * @return the value of t_client.client_email
     *
     * @mbg.generated
     */
    public String getClientEmail() {
        return clientEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_email
     *
     * @param clientEmail the value for t_client.client_email
     *
     * @mbg.generated
     */
    public void setClientEmail(String clientEmail) {
        this.clientEmail = clientEmail == null ? null : clientEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.loan_status
     *
     * @return the value of t_client.loan_status
     *
     * @mbg.generated
     */
    public Integer getLoanStatus() {
        return loanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.loan_status
     *
     * @param loanStatus the value for t_client.loan_status
     *
     * @mbg.generated
     */
    public void setLoanStatus(Integer loanStatus) {
        this.loanStatus = loanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.loan
     *
     * @return the value of t_client.loan
     *
     * @mbg.generated
     */
    public Double getLoan() {
        return loan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.loan
     *
     * @param loan the value for t_client.loan
     *
     * @mbg.generated
     */
    public void setLoan(Double loan) {
        this.loan = loan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.interview_time
     *
     * @return the value of t_client.interview_time
     *
     * @mbg.generated
     */
    public Date getInterviewTime() {
        return interviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.interview_time
     *
     * @param interviewTime the value for t_client.interview_time
     *
     * @mbg.generated
     */
    public void setInterviewTime(Date interviewTime) {
        this.interviewTime = interviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_state
     *
     * @return the value of t_client.client_state
     *
     * @mbg.generated
     */
    public Integer getClientState() {
        return clientState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_state
     *
     * @param clientState the value for t_client.client_state
     *
     * @mbg.generated
     */
    public void setClientState(Integer clientState) {
        this.clientState = clientState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.fk_profession_id
     *
     * @return the value of t_client.fk_profession_id
     *
     * @mbg.generated
     */
    public Integer getFkProfessionId() {
        return fkProfessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.fk_profession_id
     *
     * @param fkProfessionId the value for t_client.fk_profession_id
     *
     * @mbg.generated
     */
    public void setFkProfessionId(Integer fkProfessionId) {
        this.fkProfessionId = fkProfessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.major
     *
     * @return the value of t_client.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.major
     *
     * @param major the value for t_client.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.sign_time
     *
     * @return the value of t_client.sign_time
     *
     * @mbg.generated
     */
    public String getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.sign_time
     *
     * @param signTime the value for t_client.sign_time
     *
     * @mbg.generated
     */
    public void setSignTime(String signTime) {
        this.signTime = signTime == null ? null : signTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.delete
     *
     * @return the value of t_client.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.delete
     *
     * @param delete the value for t_client.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.fk_channel_id
     *
     * @return the value of t_client.fk_channel_id
     *
     * @mbg.generated
     */
    public Integer getFkChannelId() {
        return fkChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.fk_channel_id
     *
     * @param fkChannelId the value for t_client.fk_channel_id
     *
     * @mbg.generated
     */
    public void setFkChannelId(Integer fkChannelId) {
        this.fkChannelId = fkChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.version
     *
     * @return the value of t_client.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.version
     *
     * @param version the value for t_client.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.last_access_time
     *
     * @return the value of t_client.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.last_access_time
     *
     * @param lastAccessTime the value for t_client.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.fk_user_id
     *
     * @return the value of t_client.fk_user_id
     *
     * @mbg.generated
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.fk_user_id
     *
     * @param fkUserId the value for t_client.fk_user_id
     *
     * @mbg.generated
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }
}