package com.kclm.owep.entity;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_number
     *
     * @mbg.generated
     */
    private String courseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_period
     *
     * @mbg.generated
     */
    private Integer coursePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_status
     *
     * @mbg.generated
     */
    private String courseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_image
     *
     * @mbg.generated
     */
    private String courseImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_desc
     *
     * @mbg.generated
     */
    private String courseDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_open_status
     *
     * @mbg.generated
     */
    private Integer courseOpenStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.video_status
     *
     * @mbg.generated
     */
    private Integer videoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.free
     *
     * @mbg.generated
     */
    private Boolean free;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.hot
     *
     * @mbg.generated
     */
    private Boolean hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.listener
     *
     * @mbg.generated
     */
    private Boolean listener;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_type
     *
     * @mbg.generated
     */
    private String courseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.fk_course_category_id
     *
     * @mbg.generated
     */
    private Integer fkCourseCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_send_type
     *
     * @mbg.generated
     */
    private String courseSendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.id
     *
     * @return the value of t_course.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.id
     *
     * @param id the value for t_course.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_number
     *
     * @return the value of t_course.course_number
     *
     * @mbg.generated
     */
    public String getCourseNumber() {
        return courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_number
     *
     * @param courseNumber the value for t_course.course_number
     *
     * @mbg.generated
     */
    public void setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber == null ? null : courseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_name
     *
     * @return the value of t_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_name
     *
     * @param courseName the value for t_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.start_time
     *
     * @return the value of t_course.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.start_time
     *
     * @param startTime the value for t_course.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.end_time
     *
     * @return the value of t_course.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.end_time
     *
     * @param endTime the value for t_course.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_period
     *
     * @return the value of t_course.course_period
     *
     * @mbg.generated
     */
    public Integer getCoursePeriod() {
        return coursePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_period
     *
     * @param coursePeriod the value for t_course.course_period
     *
     * @mbg.generated
     */
    public void setCoursePeriod(Integer coursePeriod) {
        this.coursePeriod = coursePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_status
     *
     * @return the value of t_course.course_status
     *
     * @mbg.generated
     */
    public String getCourseStatus() {
        return courseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_status
     *
     * @param courseStatus the value for t_course.course_status
     *
     * @mbg.generated
     */
    public void setCourseStatus(String courseStatus) {
        this.courseStatus = courseStatus == null ? null : courseStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_image
     *
     * @return the value of t_course.course_image
     *
     * @mbg.generated
     */
    public String getCourseImage() {
        return courseImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_image
     *
     * @param courseImage the value for t_course.course_image
     *
     * @mbg.generated
     */
    public void setCourseImage(String courseImage) {
        this.courseImage = courseImage == null ? null : courseImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_desc
     *
     * @return the value of t_course.course_desc
     *
     * @mbg.generated
     */
    public String getCourseDesc() {
        return courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_desc
     *
     * @param courseDesc the value for t_course.course_desc
     *
     * @mbg.generated
     */
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc == null ? null : courseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.create_time
     *
     * @return the value of t_course.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.create_time
     *
     * @param createTime the value for t_course.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_open_status
     *
     * @return the value of t_course.course_open_status
     *
     * @mbg.generated
     */
    public Integer getCourseOpenStatus() {
        return courseOpenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_open_status
     *
     * @param courseOpenStatus the value for t_course.course_open_status
     *
     * @mbg.generated
     */
    public void setCourseOpenStatus(Integer courseOpenStatus) {
        this.courseOpenStatus = courseOpenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.video_status
     *
     * @return the value of t_course.video_status
     *
     * @mbg.generated
     */
    public Integer getVideoStatus() {
        return videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.video_status
     *
     * @param videoStatus the value for t_course.video_status
     *
     * @mbg.generated
     */
    public void setVideoStatus(Integer videoStatus) {
        this.videoStatus = videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.free
     *
     * @return the value of t_course.free
     *
     * @mbg.generated
     */
    public Boolean getFree() {
        return free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.free
     *
     * @param free the value for t_course.free
     *
     * @mbg.generated
     */
    public void setFree(Boolean free) {
        this.free = free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.hot
     *
     * @return the value of t_course.hot
     *
     * @mbg.generated
     */
    public Boolean getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.hot
     *
     * @param hot the value for t_course.hot
     *
     * @mbg.generated
     */
    public void setHot(Boolean hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.listener
     *
     * @return the value of t_course.listener
     *
     * @mbg.generated
     */
    public Boolean getListener() {
        return listener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.listener
     *
     * @param listener the value for t_course.listener
     *
     * @mbg.generated
     */
    public void setListener(Boolean listener) {
        this.listener = listener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_type
     *
     * @return the value of t_course.course_type
     *
     * @mbg.generated
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_type
     *
     * @param courseType the value for t_course.course_type
     *
     * @mbg.generated
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType == null ? null : courseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.fk_course_category_id
     *
     * @return the value of t_course.fk_course_category_id
     *
     * @mbg.generated
     */
    public Integer getFkCourseCategoryId() {
        return fkCourseCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.fk_course_category_id
     *
     * @param fkCourseCategoryId the value for t_course.fk_course_category_id
     *
     * @mbg.generated
     */
    public void setFkCourseCategoryId(Integer fkCourseCategoryId) {
        this.fkCourseCategoryId = fkCourseCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_send_type
     *
     * @return the value of t_course.course_send_type
     *
     * @mbg.generated
     */
    public String getCourseSendType() {
        return courseSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_send_type
     *
     * @param courseSendType the value for t_course.course_send_type
     *
     * @mbg.generated
     */
    public void setCourseSendType(String courseSendType) {
        this.courseSendType = courseSendType == null ? null : courseSendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.delete
     *
     * @return the value of t_course.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.delete
     *
     * @param delete the value for t_course.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.version
     *
     * @return the value of t_course.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.version
     *
     * @param version the value for t_course.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.last_access_time
     *
     * @return the value of t_course.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.last_access_time
     *
     * @param lastAccessTime the value for t_course.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}