package com.kclm.owep.entity;

import java.util.Date;

public class CourseComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.comment_content
     *
     * @mbg.generated
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_comment.fk_course_id
     *
     * @mbg.generated
     */
    private Integer fkCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.id
     *
     * @return the value of t_course_comment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.id
     *
     * @param id the value for t_course_comment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.comment_content
     *
     * @return the value of t_course_comment.comment_content
     *
     * @mbg.generated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.comment_content
     *
     * @param commentContent the value for t_course_comment.comment_content
     *
     * @mbg.generated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.create_time
     *
     * @return the value of t_course_comment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.create_time
     *
     * @param createTime the value for t_course_comment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.last_access_time
     *
     * @return the value of t_course_comment.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.last_access_time
     *
     * @param lastAccessTime the value for t_course_comment.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.version
     *
     * @return the value of t_course_comment.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.version
     *
     * @param version the value for t_course_comment.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.fk_student_id
     *
     * @return the value of t_course_comment.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.fk_student_id
     *
     * @param fkStudentId the value for t_course_comment.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_comment.fk_course_id
     *
     * @return the value of t_course_comment.fk_course_id
     *
     * @mbg.generated
     */
    public Integer getFkCourseId() {
        return fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_comment.fk_course_id
     *
     * @param fkCourseId the value for t_course_comment.fk_course_id
     *
     * @mbg.generated
     */
    public void setFkCourseId(Integer fkCourseId) {
        this.fkCourseId = fkCourseId;
    }
}