package com.kclm.owep.entity;

import java.util.Date;

public class CourseReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.
course_learn_count
     *
     * @mbg.generated
     */
    private Integer 
courseLearnCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.practice_count
     *
     * @mbg.generated
     */
    private Integer practiceCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.notes_count
     *
     * @mbg.generated
     */
    private Integer notesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.sign_count
     *
     * @mbg.generated
     */
    private Integer signCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.question_count
     *
     * @mbg.generated
     */
    private Integer questionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.video_play_count
     *
     * @mbg.generated
     */
    private Integer videoPlayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.answer_count
     *
     * @mbg.generated
     */
    private Integer answerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.test_count
     *
     * @mbg.generated
     */
    private Integer testCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.homework_count
     *
     * @mbg.generated
     */
    private Integer homeworkCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.homework_finished_count
     *
     * @mbg.generated
     */
    private Integer homeworkFinishedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.video_count
     *
     * @mbg.generated
     */
    private Integer videoCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.video_finished_count
     *
     * @mbg.generated
     */
    private Integer videoFinishedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.fk_course_id
     *
     * @mbg.generated
     */
    private Integer fkCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_report.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.id
     *
     * @return the value of t_course_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.id
     *
     * @param id the value for t_course_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.
course_learn_count
     *
     * @return the value of t_course_report.
course_learn_count
     *
     * @mbg.generated
     */
    public Integer getcourseLearnCount() {
        return 
        courseLearnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.
course_learn_count
     *
     * @param 
courseLearnCount the value for t_course_report.
course_learn_count
     *
     * @mbg.generated
     */
    public void setcourseLearnCount(Integer courseLearnCount) {
        this.courseLearnCount = courseLearnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.practice_count
     *
     * @return the value of t_course_report.practice_count
     *
     * @mbg.generated
     */
    public Integer getPracticeCount() {
        return practiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.practice_count
     *
     * @param practiceCount the value for t_course_report.practice_count
     *
     * @mbg.generated
     */
    public void setPracticeCount(Integer practiceCount) {
        this.practiceCount = practiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.notes_count
     *
     * @return the value of t_course_report.notes_count
     *
     * @mbg.generated
     */
    public Integer getNotesCount() {
        return notesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.notes_count
     *
     * @param notesCount the value for t_course_report.notes_count
     *
     * @mbg.generated
     */
    public void setNotesCount(Integer notesCount) {
        this.notesCount = notesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.sign_count
     *
     * @return the value of t_course_report.sign_count
     *
     * @mbg.generated
     */
    public Integer getSignCount() {
        return signCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.sign_count
     *
     * @param signCount the value for t_course_report.sign_count
     *
     * @mbg.generated
     */
    public void setSignCount(Integer signCount) {
        this.signCount = signCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.question_count
     *
     * @return the value of t_course_report.question_count
     *
     * @mbg.generated
     */
    public Integer getQuestionCount() {
        return questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.question_count
     *
     * @param questionCount the value for t_course_report.question_count
     *
     * @mbg.generated
     */
    public void setQuestionCount(Integer questionCount) {
        this.questionCount = questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.video_play_count
     *
     * @return the value of t_course_report.video_play_count
     *
     * @mbg.generated
     */
    public Integer getVideoPlayCount() {
        return videoPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.video_play_count
     *
     * @param videoPlayCount the value for t_course_report.video_play_count
     *
     * @mbg.generated
     */
    public void setVideoPlayCount(Integer videoPlayCount) {
        this.videoPlayCount = videoPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.answer_count
     *
     * @return the value of t_course_report.answer_count
     *
     * @mbg.generated
     */
    public Integer getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.answer_count
     *
     * @param answerCount the value for t_course_report.answer_count
     *
     * @mbg.generated
     */
    public void setAnswerCount(Integer answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.test_count
     *
     * @return the value of t_course_report.test_count
     *
     * @mbg.generated
     */
    public Integer getTestCount() {
        return testCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.test_count
     *
     * @param testCount the value for t_course_report.test_count
     *
     * @mbg.generated
     */
    public void setTestCount(Integer testCount) {
        this.testCount = testCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.create_time
     *
     * @return the value of t_course_report.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.create_time
     *
     * @param createTime the value for t_course_report.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.homework_count
     *
     * @return the value of t_course_report.homework_count
     *
     * @mbg.generated
     */
    public Integer getHomeworkCount() {
        return homeworkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.homework_count
     *
     * @param homeworkCount the value for t_course_report.homework_count
     *
     * @mbg.generated
     */
    public void setHomeworkCount(Integer homeworkCount) {
        this.homeworkCount = homeworkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.homework_finished_count
     *
     * @return the value of t_course_report.homework_finished_count
     *
     * @mbg.generated
     */
    public Integer getHomeworkFinishedCount() {
        return homeworkFinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.homework_finished_count
     *
     * @param homeworkFinishedCount the value for t_course_report.homework_finished_count
     *
     * @mbg.generated
     */
    public void setHomeworkFinishedCount(Integer homeworkFinishedCount) {
        this.homeworkFinishedCount = homeworkFinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.video_count
     *
     * @return the value of t_course_report.video_count
     *
     * @mbg.generated
     */
    public Integer getVideoCount() {
        return videoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.video_count
     *
     * @param videoCount the value for t_course_report.video_count
     *
     * @mbg.generated
     */
    public void setVideoCount(Integer videoCount) {
        this.videoCount = videoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.video_finished_count
     *
     * @return the value of t_course_report.video_finished_count
     *
     * @mbg.generated
     */
    public Integer getVideoFinishedCount() {
        return videoFinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.video_finished_count
     *
     * @param videoFinishedCount the value for t_course_report.video_finished_count
     *
     * @mbg.generated
     */
    public void setVideoFinishedCount(Integer videoFinishedCount) {
        this.videoFinishedCount = videoFinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.fk_student_id
     *
     * @return the value of t_course_report.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.fk_student_id
     *
     * @param fkStudentId the value for t_course_report.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.fk_course_id
     *
     * @return the value of t_course_report.fk_course_id
     *
     * @mbg.generated
     */
    public Integer getFkCourseId() {
        return fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.fk_course_id
     *
     * @param fkCourseId the value for t_course_report.fk_course_id
     *
     * @mbg.generated
     */
    public void setFkCourseId(Integer fkCourseId) {
        this.fkCourseId = fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.version
     *
     * @return the value of t_course_report.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.version
     *
     * @param version the value for t_course_report.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_report.last_access_time
     *
     * @return the value of t_course_report.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_report.last_access_time
     *
     * @param lastAccessTime the value for t_course_report.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}