package com.kclm.owep.entity;

import java.util.Date;

public class CourseCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.category_desc
     *
     * @mbg.generated
     */
    private String categoryDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.fk_parent_id
     *
     * @mbg.generated
     */
    private Integer fkParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.delete
     *
     * @mbg.generated
     */
    private String delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_category.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.id
     *
     * @return the value of t_course_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.id
     *
     * @param id the value for t_course_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.category_name
     *
     * @return the value of t_course_category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.category_name
     *
     * @param categoryName the value for t_course_category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.category_desc
     *
     * @return the value of t_course_category.category_desc
     *
     * @mbg.generated
     */
    public String getCategoryDesc() {
        return categoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.category_desc
     *
     * @param categoryDesc the value for t_course_category.category_desc
     *
     * @mbg.generated
     */
    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc == null ? null : categoryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.fk_parent_id
     *
     * @return the value of t_course_category.fk_parent_id
     *
     * @mbg.generated
     */
    public Integer getFkParentId() {
        return fkParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.fk_parent_id
     *
     * @param fkParentId the value for t_course_category.fk_parent_id
     *
     * @mbg.generated
     */
    public void setFkParentId(Integer fkParentId) {
        this.fkParentId = fkParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.create_time
     *
     * @return the value of t_course_category.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.create_time
     *
     * @param createTime the value for t_course_category.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.delete
     *
     * @return the value of t_course_category.delete
     *
     * @mbg.generated
     */
    public String getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.delete
     *
     * @param delete the value for t_course_category.delete
     *
     * @mbg.generated
     */
    public void setDelete(String delete) {
        this.delete = delete == null ? null : delete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.version
     *
     * @return the value of t_course_category.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.version
     *
     * @param version the value for t_course_category.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_category.last_access_time
     *
     * @return the value of t_course_category.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_category.last_access_time
     *
     * @param lastAccessTime the value for t_course_category.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}