package com.kclm.owep.entity;

import java.time.LocalDateTime;

/*********************
 * @Author: @TODO
 * @Version : v1.0
 * @Create: 2020年6月29日 上午10:10:40
 * @Description Dbcopy generated by hbm2java
 */
public class Dbcopy implements java.io.Serializable {

	private Integer dbcopyId;
	private String fileName;
	private String fileUrl;
	private int copyStatus;
	private int version = 1;  //版本号
	private LocalDateTime createTime = LocalDateTime.now();  //创建时间
	private LocalDateTime lastAccessTime; //最后一次访问时间

}
