package com.kclm.owep.entity;

import java.util.Date;

public class HomeworkAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.answer_url
     *
     * @mbg.generated
     */
    private String answerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.answer_content
     *
     * @mbg.generated
     */
    private String answerContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.answer_attachment
     *
     * @mbg.generated
     */
    private String answerAttachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.answer_status
     *
     * @mbg.generated
     */
    private Integer answerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.audit_content
     *
     * @mbg.generated
     */
    private String auditContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.fk_homework_id
     *
     * @mbg.generated
     */
    private Integer fkHomeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework_answer.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.id
     *
     * @return the value of t_homework_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.id
     *
     * @param id the value for t_homework_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.answer_url
     *
     * @return the value of t_homework_answer.answer_url
     *
     * @mbg.generated
     */
    public String getAnswerUrl() {
        return answerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.answer_url
     *
     * @param answerUrl the value for t_homework_answer.answer_url
     *
     * @mbg.generated
     */
    public void setAnswerUrl(String answerUrl) {
        this.answerUrl = answerUrl == null ? null : answerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.answer_content
     *
     * @return the value of t_homework_answer.answer_content
     *
     * @mbg.generated
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.answer_content
     *
     * @param answerContent the value for t_homework_answer.answer_content
     *
     * @mbg.generated
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent == null ? null : answerContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.answer_attachment
     *
     * @return the value of t_homework_answer.answer_attachment
     *
     * @mbg.generated
     */
    public String getAnswerAttachment() {
        return answerAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.answer_attachment
     *
     * @param answerAttachment the value for t_homework_answer.answer_attachment
     *
     * @mbg.generated
     */
    public void setAnswerAttachment(String answerAttachment) {
        this.answerAttachment = answerAttachment == null ? null : answerAttachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.answer_status
     *
     * @return the value of t_homework_answer.answer_status
     *
     * @mbg.generated
     */
    public Integer getAnswerStatus() {
        return answerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.answer_status
     *
     * @param answerStatus the value for t_homework_answer.answer_status
     *
     * @mbg.generated
     */
    public void setAnswerStatus(Integer answerStatus) {
        this.answerStatus = answerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.audit_content
     *
     * @return the value of t_homework_answer.audit_content
     *
     * @mbg.generated
     */
    public String getAuditContent() {
        return auditContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.audit_content
     *
     * @param auditContent the value for t_homework_answer.audit_content
     *
     * @mbg.generated
     */
    public void setAuditContent(String auditContent) {
        this.auditContent = auditContent == null ? null : auditContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.create_time
     *
     * @return the value of t_homework_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.create_time
     *
     * @param createTime the value for t_homework_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.last_access_time
     *
     * @return the value of t_homework_answer.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.last_access_time
     *
     * @param lastAccessTime the value for t_homework_answer.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.version
     *
     * @return the value of t_homework_answer.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.version
     *
     * @param version the value for t_homework_answer.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.fk_homework_id
     *
     * @return the value of t_homework_answer.fk_homework_id
     *
     * @mbg.generated
     */
    public Integer getFkHomeworkId() {
        return fkHomeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.fk_homework_id
     *
     * @param fkHomeworkId the value for t_homework_answer.fk_homework_id
     *
     * @mbg.generated
     */
    public void setFkHomeworkId(Integer fkHomeworkId) {
        this.fkHomeworkId = fkHomeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework_answer.fk_student_id
     *
     * @return the value of t_homework_answer.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework_answer.fk_student_id
     *
     * @param fkStudentId the value for t_homework_answer.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }
}