package com.kclm.owep.entity;

import java.util.Date;

public class OrgInstitute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.institute_name
     *
     * @mbg.generated
     */
    private String instituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.institute_type
     *
     * @mbg.generated
     */
    private Integer instituteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_institute.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.id
     *
     * @return the value of t_org_institute.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.id
     *
     * @param id the value for t_org_institute.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.institute_name
     *
     * @return the value of t_org_institute.institute_name
     *
     * @mbg.generated
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.institute_name
     *
     * @param instituteName the value for t_org_institute.institute_name
     *
     * @mbg.generated
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName == null ? null : instituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.institute_type
     *
     * @return the value of t_org_institute.institute_type
     *
     * @mbg.generated
     */
    public Integer getInstituteType() {
        return instituteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.institute_type
     *
     * @param instituteType the value for t_org_institute.institute_type
     *
     * @mbg.generated
     */
    public void setInstituteType(Integer instituteType) {
        this.instituteType = instituteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.delete
     *
     * @return the value of t_org_institute.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.delete
     *
     * @param delete the value for t_org_institute.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.version
     *
     * @return the value of t_org_institute.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.version
     *
     * @param version the value for t_org_institute.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.create_time
     *
     * @return the value of t_org_institute.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.create_time
     *
     * @param createTime the value for t_org_institute.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_institute.last_access_time
     *
     * @return the value of t_org_institute.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_institute.last_access_time
     *
     * @param lastAccessTime the value for t_org_institute.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}