package com.kclm.owep.entity;

import java.util.Date;

public class PlanManagerCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.fk_planmanager_id
     *
     * @mbg.generated
     */
    private Integer fkPlanmanagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.fk_course_id
     *
     * @mbg.generated
     */
    private Integer fkCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.stage_num
     *
     * @mbg.generated
     */
    private Integer stageNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.stage_name
     *
     * @mbg.generated
     */
    private Integer stageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.course_order
     *
     * @mbg.generated
     */
    private Integer courseOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager_course.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.id
     *
     * @return the value of t_planmanager_course.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.id
     *
     * @param id the value for t_planmanager_course.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.fk_planmanager_id
     *
     * @return the value of t_planmanager_course.fk_planmanager_id
     *
     * @mbg.generated
     */
    public Integer getFkPlanmanagerId() {
        return fkPlanmanagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.fk_planmanager_id
     *
     * @param fkPlanmanagerId the value for t_planmanager_course.fk_planmanager_id
     *
     * @mbg.generated
     */
    public void setFkPlanmanagerId(Integer fkPlanmanagerId) {
        this.fkPlanmanagerId = fkPlanmanagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.fk_course_id
     *
     * @return the value of t_planmanager_course.fk_course_id
     *
     * @mbg.generated
     */
    public Integer getFkCourseId() {
        return fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.fk_course_id
     *
     * @param fkCourseId the value for t_planmanager_course.fk_course_id
     *
     * @mbg.generated
     */
    public void setFkCourseId(Integer fkCourseId) {
        this.fkCourseId = fkCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.stage_num
     *
     * @return the value of t_planmanager_course.stage_num
     *
     * @mbg.generated
     */
    public Integer getStageNum() {
        return stageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.stage_num
     *
     * @param stageNum the value for t_planmanager_course.stage_num
     *
     * @mbg.generated
     */
    public void setStageNum(Integer stageNum) {
        this.stageNum = stageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.stage_name
     *
     * @return the value of t_planmanager_course.stage_name
     *
     * @mbg.generated
     */
    public Integer getStageName() {
        return stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.stage_name
     *
     * @param stageName the value for t_planmanager_course.stage_name
     *
     * @mbg.generated
     */
    public void setStageName(Integer stageName) {
        this.stageName = stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.course_order
     *
     * @return the value of t_planmanager_course.course_order
     *
     * @mbg.generated
     */
    public Integer getCourseOrder() {
        return courseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.course_order
     *
     * @param courseOrder the value for t_planmanager_course.course_order
     *
     * @mbg.generated
     */
    public void setCourseOrder(Integer courseOrder) {
        this.courseOrder = courseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.delete
     *
     * @return the value of t_planmanager_course.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.delete
     *
     * @param delete the value for t_planmanager_course.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.create_time
     *
     * @return the value of t_planmanager_course.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.create_time
     *
     * @param createTime the value for t_planmanager_course.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager_course.version
     *
     * @return the value of t_planmanager_course.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager_course.version
     *
     * @param version the value for t_planmanager_course.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}