package com.kclm.owep.entity;

import java.util.Date;

public class PlanManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.plan_number
     *
     * @mbg.generated
     */
    private String planNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.plan_name
     *
     * @mbg.generated
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.plan_status
     *
     * @mbg.generated
     */
    private Integer planStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.plan_desc
     *
     * @mbg.generated
     */
    private String planDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_planmanager.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.id
     *
     * @return the value of t_planmanager.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.id
     *
     * @param id the value for t_planmanager.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.plan_number
     *
     * @return the value of t_planmanager.plan_number
     *
     * @mbg.generated
     */
    public String getPlanNumber() {
        return planNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.plan_number
     *
     * @param planNumber the value for t_planmanager.plan_number
     *
     * @mbg.generated
     */
    public void setPlanNumber(String planNumber) {
        this.planNumber = planNumber == null ? null : planNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.plan_name
     *
     * @return the value of t_planmanager.plan_name
     *
     * @mbg.generated
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.plan_name
     *
     * @param planName the value for t_planmanager.plan_name
     *
     * @mbg.generated
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.plan_status
     *
     * @return the value of t_planmanager.plan_status
     *
     * @mbg.generated
     */
    public Integer getPlanStatus() {
        return planStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.plan_status
     *
     * @param planStatus the value for t_planmanager.plan_status
     *
     * @mbg.generated
     */
    public void setPlanStatus(Integer planStatus) {
        this.planStatus = planStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.plan_desc
     *
     * @return the value of t_planmanager.plan_desc
     *
     * @mbg.generated
     */
    public String getPlanDesc() {
        return planDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.plan_desc
     *
     * @param planDesc the value for t_planmanager.plan_desc
     *
     * @mbg.generated
     */
    public void setPlanDesc(String planDesc) {
        this.planDesc = planDesc == null ? null : planDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.delete
     *
     * @return the value of t_planmanager.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.delete
     *
     * @param delete the value for t_planmanager.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.create_time
     *
     * @return the value of t_planmanager.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.create_time
     *
     * @param createTime the value for t_planmanager.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.version
     *
     * @return the value of t_planmanager.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.version
     *
     * @param version the value for t_planmanager.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_planmanager.last_access_time
     *
     * @return the value of t_planmanager.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_planmanager.last_access_time
     *
     * @param lastAccessTime the value for t_planmanager.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}