package com.kclm.owep.entity;

import java.util.Date;

public class Profession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.prof_name
     *
     * @mbg.generated
     */
    private String profName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.prof_desc
     *
     * @mbg.generated
     */
    private String profDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.prof_status
     *
     * @mbg.generated
     */
    private Integer profStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.institute_name
     *
     * @mbg.generated
     */
    private String instituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.institute_branch_name
     *
     * @mbg.generated
     */
    private String instituteBranchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.order_profe_name
     *
     * @mbg.generated
     */
    private String orderProfeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.id
     *
     * @return the value of t_profession.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.id
     *
     * @param id the value for t_profession.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.prof_name
     *
     * @return the value of t_profession.prof_name
     *
     * @mbg.generated
     */
    public String getProfName() {
        return profName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.prof_name
     *
     * @param profName the value for t_profession.prof_name
     *
     * @mbg.generated
     */
    public void setProfName(String profName) {
        this.profName = profName == null ? null : profName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.prof_desc
     *
     * @return the value of t_profession.prof_desc
     *
     * @mbg.generated
     */
    public String getProfDesc() {
        return profDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.prof_desc
     *
     * @param profDesc the value for t_profession.prof_desc
     *
     * @mbg.generated
     */
    public void setProfDesc(String profDesc) {
        this.profDesc = profDesc == null ? null : profDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.prof_status
     *
     * @return the value of t_profession.prof_status
     *
     * @mbg.generated
     */
    public Integer getProfStatus() {
        return profStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.prof_status
     *
     * @param profStatus the value for t_profession.prof_status
     *
     * @mbg.generated
     */
    public void setProfStatus(Integer profStatus) {
        this.profStatus = profStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.institute_name
     *
     * @return the value of t_profession.institute_name
     *
     * @mbg.generated
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.institute_name
     *
     * @param instituteName the value for t_profession.institute_name
     *
     * @mbg.generated
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName == null ? null : instituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.institute_branch_name
     *
     * @return the value of t_profession.institute_branch_name
     *
     * @mbg.generated
     */
    public String getInstituteBranchName() {
        return instituteBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.institute_branch_name
     *
     * @param instituteBranchName the value for t_profession.institute_branch_name
     *
     * @mbg.generated
     */
    public void setInstituteBranchName(String instituteBranchName) {
        this.instituteBranchName = instituteBranchName == null ? null : instituteBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.delete
     *
     * @return the value of t_profession.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.delete
     *
     * @param delete the value for t_profession.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.order_profe_name
     *
     * @return the value of t_profession.order_profe_name
     *
     * @mbg.generated
     */
    public String getOrderProfeName() {
        return orderProfeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.order_profe_name
     *
     * @param orderProfeName the value for t_profession.order_profe_name
     *
     * @mbg.generated
     */
    public void setOrderProfeName(String orderProfeName) {
        this.orderProfeName = orderProfeName == null ? null : orderProfeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.version
     *
     * @return the value of t_profession.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.version
     *
     * @param version the value for t_profession.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.create_time
     *
     * @return the value of t_profession.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.create_time
     *
     * @param createTime the value for t_profession.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.last_access_time
     *
     * @return the value of t_profession.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.last_access_time
     *
     * @param lastAccessTime the value for t_profession.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}