package com.kclm.owep.entity;

import java.util.Date;

public class Section {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.
section_name
     *
     * @mbg.generated
     */
    private String 
sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.section_number
     *
     * @mbg.generated
     */
    private String sectionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.section_desc
     *
     * @mbg.generated
     */
    private String sectionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.video_status
     *
     * @mbg.generated
     */
    private Integer videoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.fk_chapter_id
     *
     * @mbg.generated
     */
    private Integer fkChapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.experiment_ducument_file
     *
     * @mbg.generated
     */
    private String experimentDucumentFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.experiment_environment_addr
     *
     * @mbg.generated
     */
    private String experimentEnvironmentAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.experiment
     *
     * @mbg.generated
     */
    private Integer experiment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.look_video_status
     *
     * @mbg.generated
     */
    private Integer lookVideoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section.experiment_instrusction
     *
     * @mbg.generated
     */
    private String experimentInstrusction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.id
     *
     * @return the value of t_section.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.id
     *
     * @param id the value for t_section.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.
section_name
     *
     * @return the value of t_section.
section_name
     *
     * @mbg.generated
     */
    public String get
sectionName() {
        return 
sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.
section_name
     *
     * @param 
sectionName the value for t_section.
section_name
     *
     * @mbg.generated
     */
    public void set
sectionName(String 
sectionName) {
        this.
sectionName = 
sectionName == null ? null : 
sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.section_number
     *
     * @return the value of t_section.section_number
     *
     * @mbg.generated
     */
    public String getSectionNumber() {
        return sectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.section_number
     *
     * @param sectionNumber the value for t_section.section_number
     *
     * @mbg.generated
     */
    public void setSectionNumber(String sectionNumber) {
        this.sectionNumber = sectionNumber == null ? null : sectionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.section_desc
     *
     * @return the value of t_section.section_desc
     *
     * @mbg.generated
     */
    public String getSectionDesc() {
        return sectionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.section_desc
     *
     * @param sectionDesc the value for t_section.section_desc
     *
     * @mbg.generated
     */
    public void setSectionDesc(String sectionDesc) {
        this.sectionDesc = sectionDesc == null ? null : sectionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.create_time
     *
     * @return the value of t_section.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.create_time
     *
     * @param createTime the value for t_section.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.video_status
     *
     * @return the value of t_section.video_status
     *
     * @mbg.generated
     */
    public Integer getVideoStatus() {
        return videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.video_status
     *
     * @param videoStatus the value for t_section.video_status
     *
     * @mbg.generated
     */
    public void setVideoStatus(Integer videoStatus) {
        this.videoStatus = videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.fk_chapter_id
     *
     * @return the value of t_section.fk_chapter_id
     *
     * @mbg.generated
     */
    public Integer getFkChapterId() {
        return fkChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.fk_chapter_id
     *
     * @param fkChapterId the value for t_section.fk_chapter_id
     *
     * @mbg.generated
     */
    public void setFkChapterId(Integer fkChapterId) {
        this.fkChapterId = fkChapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.delete
     *
     * @return the value of t_section.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.delete
     *
     * @param delete the value for t_section.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.experiment_ducument_file
     *
     * @return the value of t_section.experiment_ducument_file
     *
     * @mbg.generated
     */
    public String getExperimentDucumentFile() {
        return experimentDucumentFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.experiment_ducument_file
     *
     * @param experimentDucumentFile the value for t_section.experiment_ducument_file
     *
     * @mbg.generated
     */
    public void setExperimentDucumentFile(String experimentDucumentFile) {
        this.experimentDucumentFile = experimentDucumentFile == null ? null : experimentDucumentFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.experiment_environment_addr
     *
     * @return the value of t_section.experiment_environment_addr
     *
     * @mbg.generated
     */
    public String getExperimentEnvironmentAddr() {
        return experimentEnvironmentAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.experiment_environment_addr
     *
     * @param experimentEnvironmentAddr the value for t_section.experiment_environment_addr
     *
     * @mbg.generated
     */
    public void setExperimentEnvironmentAddr(String experimentEnvironmentAddr) {
        this.experimentEnvironmentAddr = experimentEnvironmentAddr == null ? null : experimentEnvironmentAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.experiment
     *
     * @return the value of t_section.experiment
     *
     * @mbg.generated
     */
    public Integer getExperiment() {
        return experiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.experiment
     *
     * @param experiment the value for t_section.experiment
     *
     * @mbg.generated
     */
    public void setExperiment(Integer experiment) {
        this.experiment = experiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.look_video_status
     *
     * @return the value of t_section.look_video_status
     *
     * @mbg.generated
     */
    public Integer getLookVideoStatus() {
        return lookVideoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.look_video_status
     *
     * @param lookVideoStatus the value for t_section.look_video_status
     *
     * @mbg.generated
     */
    public void setLookVideoStatus(Integer lookVideoStatus) {
        this.lookVideoStatus = lookVideoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.version
     *
     * @return the value of t_section.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.version
     *
     * @param version the value for t_section.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.last_access_time
     *
     * @return the value of t_section.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.last_access_time
     *
     * @param lastAccessTime the value for t_section.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section.experiment_instrusction
     *
     * @return the value of t_section.experiment_instrusction
     *
     * @mbg.generated
     */
    public String getExperimentInstrusction() {
        return experimentInstrusction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section.experiment_instrusction
     *
     * @param experimentInstrusction the value for t_section.experiment_instrusction
     *
     * @mbg.generated
     */
    public void setExperimentInstrusction(String experimentInstrusction) {
        this.experimentInstrusction = experimentInstrusction == null ? null : experimentInstrusction.trim();
    }
}