package com.kclm.owep.entity;

import java.util.Date;

public class SectionVideo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section_video.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section_video.fk_section_id
     *
     * @mbg.generated
     */
    private Integer fkSectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section_video.fk_video_id
     *
     * @mbg.generated
     */
    private Integer fkVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section_video.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section_video.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_section_video.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section_video.id
     *
     * @return the value of t_section_video.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section_video.id
     *
     * @param id the value for t_section_video.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section_video.fk_section_id
     *
     * @return the value of t_section_video.fk_section_id
     *
     * @mbg.generated
     */
    public Integer getFkSectionId() {
        return fkSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section_video.fk_section_id
     *
     * @param fkSectionId the value for t_section_video.fk_section_id
     *
     * @mbg.generated
     */
    public void setFkSectionId(Integer fkSectionId) {
        this.fkSectionId = fkSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section_video.fk_video_id
     *
     * @return the value of t_section_video.fk_video_id
     *
     * @mbg.generated
     */
    public Integer getFkVideoId() {
        return fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section_video.fk_video_id
     *
     * @param fkVideoId the value for t_section_video.fk_video_id
     *
     * @mbg.generated
     */
    public void setFkVideoId(Integer fkVideoId) {
        this.fkVideoId = fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section_video.create_time
     *
     * @return the value of t_section_video.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section_video.create_time
     *
     * @param createTime the value for t_section_video.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section_video.last_access_time
     *
     * @return the value of t_section_video.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section_video.last_access_time
     *
     * @param lastAccessTime the value for t_section_video.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_section_video.version
     *
     * @return the value of t_section_video.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_section_video.version
     *
     * @param version the value for t_section_video.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}