package com.kclm.owep.entity;

import java.util.Date;

public class StudyRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.progress_status
     *
     * @mbg.generated
     */
    private Integer progressStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.fk_section_id
     *
     * @mbg.generated
     */
    private Integer fkSectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.chapter_name
     *
     * @mbg.generated
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.section_name
     *
     * @mbg.generated
     */
    private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.video_rate
     *
     * @mbg.generated
     */
    private Double videoRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.video_length
     *
     * @mbg.generated
     */
    private Integer videoLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_studyrecord.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.id
     *
     * @return the value of t_studyrecord.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.id
     *
     * @param id the value for t_studyrecord.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.progress_status
     *
     * @return the value of t_studyrecord.progress_status
     *
     * @mbg.generated
     */
    public Integer getProgressStatus() {
        return progressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.progress_status
     *
     * @param progressStatus the value for t_studyrecord.progress_status
     *
     * @mbg.generated
     */
    public void setProgressStatus(Integer progressStatus) {
        this.progressStatus = progressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.create_time
     *
     * @return the value of t_studyrecord.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.create_time
     *
     * @param createTime the value for t_studyrecord.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.fk_student_id
     *
     * @return the value of t_studyrecord.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.fk_student_id
     *
     * @param fkStudentId the value for t_studyrecord.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.fk_section_id
     *
     * @return the value of t_studyrecord.fk_section_id
     *
     * @mbg.generated
     */
    public Integer getFkSectionId() {
        return fkSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.fk_section_id
     *
     * @param fkSectionId the value for t_studyrecord.fk_section_id
     *
     * @mbg.generated
     */
    public void setFkSectionId(Integer fkSectionId) {
        this.fkSectionId = fkSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.course_name
     *
     * @return the value of t_studyrecord.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.course_name
     *
     * @param courseName the value for t_studyrecord.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.chapter_name
     *
     * @return the value of t_studyrecord.chapter_name
     *
     * @mbg.generated
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.chapter_name
     *
     * @param chapterName the value for t_studyrecord.chapter_name
     *
     * @mbg.generated
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.section_name
     *
     * @return the value of t_studyrecord.section_name
     *
     * @mbg.generated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.section_name
     *
     * @param sectionName the value for t_studyrecord.section_name
     *
     * @mbg.generated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.video_rate
     *
     * @return the value of t_studyrecord.video_rate
     *
     * @mbg.generated
     */
    public Double getVideoRate() {
        return videoRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.video_rate
     *
     * @param videoRate the value for t_studyrecord.video_rate
     *
     * @mbg.generated
     */
    public void setVideoRate(Double videoRate) {
        this.videoRate = videoRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.video_length
     *
     * @return the value of t_studyrecord.video_length
     *
     * @mbg.generated
     */
    public Integer getVideoLength() {
        return videoLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.video_length
     *
     * @param videoLength the value for t_studyrecord.video_length
     *
     * @mbg.generated
     */
    public void setVideoLength(Integer videoLength) {
        this.videoLength = videoLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.version
     *
     * @return the value of t_studyrecord.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.version
     *
     * @param version the value for t_studyrecord.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_studyrecord.last_access_time
     *
     * @return the value of t_studyrecord.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_studyrecord.last_access_time
     *
     * @param lastAccessTime the value for t_studyrecord.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}