package com.kclm.owep.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_name
     *
     * @mbg.generated
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_pwd
     *
     * @mbg.generated
     */
    private String stuPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_phone
     *
     * @mbg.generated
     */
    private String stuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_email
     *
     * @mbg.generated
     */
    private String stuEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_real_name
     *
     * @mbg.generated
     */
    private String stuRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.email_code
     *
     * @mbg.generated
     */
    private String emailCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.card_num
     *
     * @mbg.generated
     */
    private String cardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.effective_date
     *
     * @mbg.generated
     */
    private Date effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.birth
     *
     * @mbg.generated
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_type
     *
     * @mbg.generated
     */
    private String stuType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_school
     *
     * @mbg.generated
     */
    private String stuSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_college
     *
     * @mbg.generated
     */
    private String stuCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_major
     *
     * @mbg.generated
     */
    private String stuMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_education
     *
     * @mbg.generated
     */
    private Integer stuEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.english_level
     *
     * @mbg.generated
     */
    private Integer englishLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.perfect_status
     *
     * @mbg.generated
     */
    private Integer perfectStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.fk_class_id
     *
     * @mbg.generated
     */
    private Integer fkClassId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_name
     *
     * @return the value of t_student.stu_name
     *
     * @mbg.generated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_name
     *
     * @param stuName the value for t_student.stu_name
     *
     * @mbg.generated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_pwd
     *
     * @return the value of t_student.stu_pwd
     *
     * @mbg.generated
     */
    public String getStuPwd() {
        return stuPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_pwd
     *
     * @param stuPwd the value for t_student.stu_pwd
     *
     * @mbg.generated
     */
    public void setStuPwd(String stuPwd) {
        this.stuPwd = stuPwd == null ? null : stuPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_phone
     *
     * @return the value of t_student.stu_phone
     *
     * @mbg.generated
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_phone
     *
     * @param stuPhone the value for t_student.stu_phone
     *
     * @mbg.generated
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_email
     *
     * @return the value of t_student.stu_email
     *
     * @mbg.generated
     */
    public String getStuEmail() {
        return stuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_email
     *
     * @param stuEmail the value for t_student.stu_email
     *
     * @mbg.generated
     */
    public void setStuEmail(String stuEmail) {
        this.stuEmail = stuEmail == null ? null : stuEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_real_name
     *
     * @return the value of t_student.stu_real_name
     *
     * @mbg.generated
     */
    public String getStuRealName() {
        return stuRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_real_name
     *
     * @param stuRealName the value for t_student.stu_real_name
     *
     * @mbg.generated
     */
    public void setStuRealName(String stuRealName) {
        this.stuRealName = stuRealName == null ? null : stuRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.email_code
     *
     * @return the value of t_student.email_code
     *
     * @mbg.generated
     */
    public String getEmailCode() {
        return emailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.email_code
     *
     * @param emailCode the value for t_student.email_code
     *
     * @mbg.generated
     */
    public void setEmailCode(String emailCode) {
        this.emailCode = emailCode == null ? null : emailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.gender
     *
     * @return the value of t_student.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.gender
     *
     * @param gender the value for t_student.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.card_num
     *
     * @return the value of t_student.card_num
     *
     * @mbg.generated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.card_num
     *
     * @param cardNum the value for t_student.card_num
     *
     * @mbg.generated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.status
     *
     * @return the value of t_student.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.status
     *
     * @param status the value for t_student.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.effective_date
     *
     * @return the value of t_student.effective_date
     *
     * @mbg.generated
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.effective_date
     *
     * @param effectiveDate the value for t_student.effective_date
     *
     * @mbg.generated
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.birth
     *
     * @return the value of t_student.birth
     *
     * @mbg.generated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.birth
     *
     * @param birth the value for t_student.birth
     *
     * @mbg.generated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.image_url
     *
     * @return the value of t_student.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.image_url
     *
     * @param imageUrl the value for t_student.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.description
     *
     * @return the value of t_student.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.description
     *
     * @param description the value for t_student.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_type
     *
     * @return the value of t_student.stu_type
     *
     * @mbg.generated
     */
    public String getStuType() {
        return stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_type
     *
     * @param stuType the value for t_student.stu_type
     *
     * @mbg.generated
     */
    public void setStuType(String stuType) {
        this.stuType = stuType == null ? null : stuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_school
     *
     * @return the value of t_student.stu_school
     *
     * @mbg.generated
     */
    public String getStuSchool() {
        return stuSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_school
     *
     * @param stuSchool the value for t_student.stu_school
     *
     * @mbg.generated
     */
    public void setStuSchool(String stuSchool) {
        this.stuSchool = stuSchool == null ? null : stuSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_college
     *
     * @return the value of t_student.stu_college
     *
     * @mbg.generated
     */
    public String getStuCollege() {
        return stuCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_college
     *
     * @param stuCollege the value for t_student.stu_college
     *
     * @mbg.generated
     */
    public void setStuCollege(String stuCollege) {
        this.stuCollege = stuCollege == null ? null : stuCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_major
     *
     * @return the value of t_student.stu_major
     *
     * @mbg.generated
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_major
     *
     * @param stuMajor the value for t_student.stu_major
     *
     * @mbg.generated
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_education
     *
     * @return the value of t_student.stu_education
     *
     * @mbg.generated
     */
    public Integer getStuEducation() {
        return stuEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_education
     *
     * @param stuEducation the value for t_student.stu_education
     *
     * @mbg.generated
     */
    public void setStuEducation(Integer stuEducation) {
        this.stuEducation = stuEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.english_level
     *
     * @return the value of t_student.english_level
     *
     * @mbg.generated
     */
    public Integer getEnglishLevel() {
        return englishLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.english_level
     *
     * @param englishLevel the value for t_student.english_level
     *
     * @mbg.generated
     */
    public void setEnglishLevel(Integer englishLevel) {
        this.englishLevel = englishLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.perfect_status
     *
     * @return the value of t_student.perfect_status
     *
     * @mbg.generated
     */
    public Integer getPerfectStatus() {
        return perfectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.perfect_status
     *
     * @param perfectStatus the value for t_student.perfect_status
     *
     * @mbg.generated
     */
    public void setPerfectStatus(Integer perfectStatus) {
        this.perfectStatus = perfectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.is_delete
     *
     * @return the value of t_student.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.is_delete
     *
     * @param isDelete the value for t_student.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.create_time
     *
     * @return the value of t_student.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.create_time
     *
     * @param createTime the value for t_student.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.last_access_time
     *
     * @return the value of t_student.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.last_access_time
     *
     * @param lastAccessTime the value for t_student.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.version
     *
     * @return the value of t_student.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.version
     *
     * @param version the value for t_student.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.fk_class_id
     *
     * @return the value of t_student.fk_class_id
     *
     * @mbg.generated
     */
    public Integer getFkClassId() {
        return fkClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.fk_class_id
     *
     * @param fkClassId the value for t_student.fk_class_id
     *
     * @mbg.generated
     */
    public void setFkClassId(Integer fkClassId) {
        this.fkClassId = fkClassId;
    }
}