package com.kclm.owep.entity;

import java.util.Date;

public class StudentReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.chapter_name
     *
     * @mbg.generated
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.section_name
     *
     * @mbg.generated
     */
    private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.video_study_time
     *
     * @mbg.generated
     */
    private Integer videoStudyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.homework_count
     *
     * @mbg.generated
     */
    private Integer homeworkCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.question_count
     *
     * @mbg.generated
     */
    private Integer questionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.leave_count
     *
     * @mbg.generated
     */
    private Integer leaveCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.illegal_count
     *
     * @mbg.generated
     */
    private Integer illegalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.note_count
     *
     * @mbg.generated
     */
    private Integer noteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.exam_count
     *
     * @mbg.generated
     */
    private Integer examCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student_report.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.id
     *
     * @return the value of t_student_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.id
     *
     * @param id the value for t_student_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.create_time
     *
     * @return the value of t_student_report.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.create_time
     *
     * @param createTime the value for t_student_report.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.course_name
     *
     * @return the value of t_student_report.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.course_name
     *
     * @param courseName the value for t_student_report.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.chapter_name
     *
     * @return the value of t_student_report.chapter_name
     *
     * @mbg.generated
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.chapter_name
     *
     * @param chapterName the value for t_student_report.chapter_name
     *
     * @mbg.generated
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.section_name
     *
     * @return the value of t_student_report.section_name
     *
     * @mbg.generated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.section_name
     *
     * @param sectionName the value for t_student_report.section_name
     *
     * @mbg.generated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.video_study_time
     *
     * @return the value of t_student_report.video_study_time
     *
     * @mbg.generated
     */
    public Integer getVideoStudyTime() {
        return videoStudyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.video_study_time
     *
     * @param videoStudyTime the value for t_student_report.video_study_time
     *
     * @mbg.generated
     */
    public void setVideoStudyTime(Integer videoStudyTime) {
        this.videoStudyTime = videoStudyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.homework_count
     *
     * @return the value of t_student_report.homework_count
     *
     * @mbg.generated
     */
    public Integer getHomeworkCount() {
        return homeworkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.homework_count
     *
     * @param homeworkCount the value for t_student_report.homework_count
     *
     * @mbg.generated
     */
    public void setHomeworkCount(Integer homeworkCount) {
        this.homeworkCount = homeworkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.question_count
     *
     * @return the value of t_student_report.question_count
     *
     * @mbg.generated
     */
    public Integer getQuestionCount() {
        return questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.question_count
     *
     * @param questionCount the value for t_student_report.question_count
     *
     * @mbg.generated
     */
    public void setQuestionCount(Integer questionCount) {
        this.questionCount = questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.leave_count
     *
     * @return the value of t_student_report.leave_count
     *
     * @mbg.generated
     */
    public Integer getLeaveCount() {
        return leaveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.leave_count
     *
     * @param leaveCount the value for t_student_report.leave_count
     *
     * @mbg.generated
     */
    public void setLeaveCount(Integer leaveCount) {
        this.leaveCount = leaveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.illegal_count
     *
     * @return the value of t_student_report.illegal_count
     *
     * @mbg.generated
     */
    public Integer getIllegalCount() {
        return illegalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.illegal_count
     *
     * @param illegalCount the value for t_student_report.illegal_count
     *
     * @mbg.generated
     */
    public void setIllegalCount(Integer illegalCount) {
        this.illegalCount = illegalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.note_count
     *
     * @return the value of t_student_report.note_count
     *
     * @mbg.generated
     */
    public Integer getNoteCount() {
        return noteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.note_count
     *
     * @param noteCount the value for t_student_report.note_count
     *
     * @mbg.generated
     */
    public void setNoteCount(Integer noteCount) {
        this.noteCount = noteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.exam_count
     *
     * @return the value of t_student_report.exam_count
     *
     * @mbg.generated
     */
    public Integer getExamCount() {
        return examCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.exam_count
     *
     * @param examCount the value for t_student_report.exam_count
     *
     * @mbg.generated
     */
    public void setExamCount(Integer examCount) {
        this.examCount = examCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.fk_student_id
     *
     * @return the value of t_student_report.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.fk_student_id
     *
     * @param fkStudentId the value for t_student_report.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.last_access_time
     *
     * @return the value of t_student_report.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.last_access_time
     *
     * @param lastAccessTime the value for t_student_report.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student_report.version
     *
     * @return the value of t_student_report.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student_report.version
     *
     * @param version the value for t_student_report.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}