package com.kclm.owep.entity;

import java.util.Date;

public class SystemConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.system_name
     *
     * @mbg.generated
     */
    private String systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.copy_name
     *
     * @mbg.generated
     */
    private String copyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.login_page_logo
     *
     * @mbg.generated
     */
    private String loginPageLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.system_page_logo
     *
     * @mbg.generated
     */
    private String systemPageLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_config.login_count
     *
     * @mbg.generated
     */
    private Integer loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.id
     *
     * @return the value of t_system_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.id
     *
     * @param id the value for t_system_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.system_name
     *
     * @return the value of t_system_config.system_name
     *
     * @mbg.generated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.system_name
     *
     * @param systemName the value for t_system_config.system_name
     *
     * @mbg.generated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.copy_name
     *
     * @return the value of t_system_config.copy_name
     *
     * @mbg.generated
     */
    public String getCopyName() {
        return copyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.copy_name
     *
     * @param copyName the value for t_system_config.copy_name
     *
     * @mbg.generated
     */
    public void setCopyName(String copyName) {
        this.copyName = copyName == null ? null : copyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.login_page_logo
     *
     * @return the value of t_system_config.login_page_logo
     *
     * @mbg.generated
     */
    public String getLoginPageLogo() {
        return loginPageLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.login_page_logo
     *
     * @param loginPageLogo the value for t_system_config.login_page_logo
     *
     * @mbg.generated
     */
    public void setLoginPageLogo(String loginPageLogo) {
        this.loginPageLogo = loginPageLogo == null ? null : loginPageLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.system_page_logo
     *
     * @return the value of t_system_config.system_page_logo
     *
     * @mbg.generated
     */
    public String getSystemPageLogo() {
        return systemPageLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.system_page_logo
     *
     * @param systemPageLogo the value for t_system_config.system_page_logo
     *
     * @mbg.generated
     */
    public void setSystemPageLogo(String systemPageLogo) {
        this.systemPageLogo = systemPageLogo == null ? null : systemPageLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.create_time
     *
     * @return the value of t_system_config.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.create_time
     *
     * @param createTime the value for t_system_config.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.version
     *
     * @return the value of t_system_config.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.version
     *
     * @param version the value for t_system_config.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.last_access_time
     *
     * @return the value of t_system_config.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.last_access_time
     *
     * @param lastAccessTime the value for t_system_config.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_config.login_count
     *
     * @return the value of t_system_config.login_count
     *
     * @mbg.generated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_config.login_count
     *
     * @param loginCount the value for t_system_config.login_count
     *
     * @mbg.generated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }
}