package com.kclm.owep.entity;

import java.util.Date;

public class VideoQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.question_content
     *
     * @mbg.generated
     */
    private String questionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.question_type
     *
     * @mbg.generated
     */
    private Integer questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.question_author
     *
     * @mbg.generated
     */
    private String questionAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.favour_count
     *
     * @mbg.generated
     */
    private Integer favourCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_question.fk_video_id
     *
     * @mbg.generated
     */
    private Integer fkVideoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.id
     *
     * @return the value of t_video_question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.id
     *
     * @param id the value for t_video_question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.create_time
     *
     * @return the value of t_video_question.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.create_time
     *
     * @param createTime the value for t_video_question.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.question_content
     *
     * @return the value of t_video_question.question_content
     *
     * @mbg.generated
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.question_content
     *
     * @param questionContent the value for t_video_question.question_content
     *
     * @mbg.generated
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent == null ? null : questionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.question_type
     *
     * @return the value of t_video_question.question_type
     *
     * @mbg.generated
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.question_type
     *
     * @param questionType the value for t_video_question.question_type
     *
     * @mbg.generated
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.question_author
     *
     * @return the value of t_video_question.question_author
     *
     * @mbg.generated
     */
    public String getQuestionAuthor() {
        return questionAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.question_author
     *
     * @param questionAuthor the value for t_video_question.question_author
     *
     * @mbg.generated
     */
    public void setQuestionAuthor(String questionAuthor) {
        this.questionAuthor = questionAuthor == null ? null : questionAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.favour_count
     *
     * @return the value of t_video_question.favour_count
     *
     * @mbg.generated
     */
    public Integer getFavourCount() {
        return favourCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.favour_count
     *
     * @param favourCount the value for t_video_question.favour_count
     *
     * @mbg.generated
     */
    public void setFavourCount(Integer favourCount) {
        this.favourCount = favourCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.last_access_time
     *
     * @return the value of t_video_question.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.last_access_time
     *
     * @param lastAccessTime the value for t_video_question.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.version
     *
     * @return the value of t_video_question.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.version
     *
     * @param version the value for t_video_question.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_question.fk_video_id
     *
     * @return the value of t_video_question.fk_video_id
     *
     * @mbg.generated
     */
    public Integer getFkVideoId() {
        return fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_question.fk_video_id
     *
     * @param fkVideoId the value for t_video_question.fk_video_id
     *
     * @mbg.generated
     */
    public void setFkVideoId(Integer fkVideoId) {
        this.fkVideoId = fkVideoId;
    }
}