package com.kclm.owep.entity;

import java.util.Date;

public class VideoCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.fk_student_id
     *
     * @mbg.generated
     */
    private Integer fkStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.fk_section_id
     *
     * @mbg.generated
     */
    private Integer fkSectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.fk_video_id
     *
     * @mbg.generated
     */
    private Integer fkVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.chapter_name
     *
     * @mbg.generated
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.section_name
     *
     * @mbg.generated
     */
    private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video_collect.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.id
     *
     * @return the value of t_video_collect.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.id
     *
     * @param id the value for t_video_collect.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.fk_student_id
     *
     * @return the value of t_video_collect.fk_student_id
     *
     * @mbg.generated
     */
    public Integer getFkStudentId() {
        return fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.fk_student_id
     *
     * @param fkStudentId the value for t_video_collect.fk_student_id
     *
     * @mbg.generated
     */
    public void setFkStudentId(Integer fkStudentId) {
        this.fkStudentId = fkStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.fk_section_id
     *
     * @return the value of t_video_collect.fk_section_id
     *
     * @mbg.generated
     */
    public Integer getFkSectionId() {
        return fkSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.fk_section_id
     *
     * @param fkSectionId the value for t_video_collect.fk_section_id
     *
     * @mbg.generated
     */
    public void setFkSectionId(Integer fkSectionId) {
        this.fkSectionId = fkSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.fk_video_id
     *
     * @return the value of t_video_collect.fk_video_id
     *
     * @mbg.generated
     */
    public Integer getFkVideoId() {
        return fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.fk_video_id
     *
     * @param fkVideoId the value for t_video_collect.fk_video_id
     *
     * @mbg.generated
     */
    public void setFkVideoId(Integer fkVideoId) {
        this.fkVideoId = fkVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.course_name
     *
     * @return the value of t_video_collect.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.course_name
     *
     * @param courseName the value for t_video_collect.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.chapter_name
     *
     * @return the value of t_video_collect.chapter_name
     *
     * @mbg.generated
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.chapter_name
     *
     * @param chapterName the value for t_video_collect.chapter_name
     *
     * @mbg.generated
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.section_name
     *
     * @return the value of t_video_collect.section_name
     *
     * @mbg.generated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.section_name
     *
     * @param sectionName the value for t_video_collect.section_name
     *
     * @mbg.generated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.create_time
     *
     * @return the value of t_video_collect.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.create_time
     *
     * @param createTime the value for t_video_collect.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.last_access_time
     *
     * @return the value of t_video_collect.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.last_access_time
     *
     * @param lastAccessTime the value for t_video_collect.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video_collect.version
     *
     * @return the value of t_video_collect.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video_collect.version
     *
     * @param version the value for t_video_collect.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}