package com.kclm.owep.entity;

import java.util.Date;

public class VideoWatchHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_videowatch_history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_videowatch_history.fk_study_record_id
     *
     * @mbg.generated
     */
    private Integer fkStudyRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_videowatch_history.watch_position
     *
     * @mbg.generated
     */
    private Double watchPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_videowatch_history.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_videowatch_history.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_videowatch_history.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_videowatch_history.id
     *
     * @return the value of t_videowatch_history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_videowatch_history.id
     *
     * @param id the value for t_videowatch_history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_videowatch_history.fk_study_record_id
     *
     * @return the value of t_videowatch_history.fk_study_record_id
     *
     * @mbg.generated
     */
    public Integer getFkStudyRecordId() {
        return fkStudyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_videowatch_history.fk_study_record_id
     *
     * @param fkStudyRecordId the value for t_videowatch_history.fk_study_record_id
     *
     * @mbg.generated
     */
    public void setFkStudyRecordId(Integer fkStudyRecordId) {
        this.fkStudyRecordId = fkStudyRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_videowatch_history.watch_position
     *
     * @return the value of t_videowatch_history.watch_position
     *
     * @mbg.generated
     */
    public Double getWatchPosition() {
        return watchPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_videowatch_history.watch_position
     *
     * @param watchPosition the value for t_videowatch_history.watch_position
     *
     * @mbg.generated
     */
    public void setWatchPosition(Double watchPosition) {
        this.watchPosition = watchPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_videowatch_history.create_time
     *
     * @return the value of t_videowatch_history.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_videowatch_history.create_time
     *
     * @param createTime the value for t_videowatch_history.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_videowatch_history.last_access_time
     *
     * @return the value of t_videowatch_history.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_videowatch_history.last_access_time
     *
     * @param lastAccessTime the value for t_videowatch_history.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_videowatch_history.version
     *
     * @return the value of t_videowatch_history.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_videowatch_history.version
     *
     * @param version the value for t_videowatch_history.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}