package com.kclm.owep.entity;

import java.util.Date;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.fk_parent_id
     *
     * @mbg.generated
     */
    private Integer fkParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_length
     *
     * @mbg.generated
     */
    private Double videoLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_from
     *
     * @mbg.generated
     */
    private String videoFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_url
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_desc
     *
     * @mbg.generated
     */
    private String videoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.delete
     *
     * @mbg.generated
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.last_access_time
     *
     * @mbg.generated
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.id
     *
     * @return the value of t_video.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.id
     *
     * @param id the value for t_video.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_name
     *
     * @return the value of t_video.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_name
     *
     * @param videoName the value for t_video.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.type
     *
     * @return the value of t_video.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.type
     *
     * @param type the value for t_video.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.fk_parent_id
     *
     * @return the value of t_video.fk_parent_id
     *
     * @mbg.generated
     */
    public Integer getFkParentId() {
        return fkParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.fk_parent_id
     *
     * @param fkParentId the value for t_video.fk_parent_id
     *
     * @mbg.generated
     */
    public void setFkParentId(Integer fkParentId) {
        this.fkParentId = fkParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_length
     *
     * @return the value of t_video.video_length
     *
     * @mbg.generated
     */
    public Double getVideoLength() {
        return videoLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_length
     *
     * @param videoLength the value for t_video.video_length
     *
     * @mbg.generated
     */
    public void setVideoLength(Double videoLength) {
        this.videoLength = videoLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_from
     *
     * @return the value of t_video.video_from
     *
     * @mbg.generated
     */
    public String getVideoFrom() {
        return videoFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_from
     *
     * @param videoFrom the value for t_video.video_from
     *
     * @mbg.generated
     */
    public void setVideoFrom(String videoFrom) {
        this.videoFrom = videoFrom == null ? null : videoFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.status
     *
     * @return the value of t_video.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.status
     *
     * @param status the value for t_video.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_url
     *
     * @return the value of t_video.video_url
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_url
     *
     * @param videoUrl the value for t_video.video_url
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_desc
     *
     * @return the value of t_video.video_desc
     *
     * @mbg.generated
     */
    public String getVideoDesc() {
        return videoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_desc
     *
     * @param videoDesc the value for t_video.video_desc
     *
     * @mbg.generated
     */
    public void setVideoDesc(String videoDesc) {
        this.videoDesc = videoDesc == null ? null : videoDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.delete
     *
     * @return the value of t_video.delete
     *
     * @mbg.generated
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.delete
     *
     * @param delete the value for t_video.delete
     *
     * @mbg.generated
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.create_time
     *
     * @return the value of t_video.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.create_time
     *
     * @param createTime the value for t_video.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.last_access_time
     *
     * @return the value of t_video.last_access_time
     *
     * @mbg.generated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.last_access_time
     *
     * @param lastAccessTime the value for t_video.last_access_time
     *
     * @mbg.generated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.version
     *
     * @return the value of t_video.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.version
     *
     * @param version the value for t_video.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}